const MAX_RELICS_PER_UNIT = 6;

const RELICS = [
  {
    id: "storm_capacitor",
    name: "风暴电容",
    rarity: "rare",
    trigger: "onDamageType:lightning",
    description: "触发闪电伤害时，本场闪电伤害增幅 +1%，可叠加。",
    effect: { addBattleStack: { stat: "lightningDamageAmp", value: 0.01, maxStacks: 50 } },
  },
  {
    id: "long_burning_wick",
    name: "长燃灯芯",
    rarity: "uncommon",
    trigger: "onApplyDot:fire",
    description: "火焰持续伤害时间 +50%。",
    effect: { modifyPacket: { stat: "fireDurationAmp", value: 0.5 } },
  },
  {
    id: "ember_crit_core",
    name: "爆燃核心",
    rarity: "epic",
    trigger: "onCrit",
    description: "暴击时引发一次范围火焰伤害。",
    effect: { createAreaDamage: { type: "fire", scaleFromAttack: 0.35, radius: 80 } },
  },
  {
    id: "venom_bloom",
    name: "毒花孢子",
    rarity: "rare",
    trigger: "onKill:poisoned",
    description: "中毒目标死亡时，将剩余剧毒扩散给附近敌人。",
    effect: { spreadDot: { type: "poison", ratio: 0.45, radius: 95 } },
  },
  {
    id: "execution_rhythm",
    name: "处决节奏",
    rarity: "uncommon",
    trigger: "onHit:sameTarget",
    description: "连续攻击同一目标时，物理伤害增幅逐层提高。",
    effect: { addTargetStack: { stat: "physicalDamageAmp", value: 0.025, maxStacks: 12 } },
  },
  {
    id: "frost_shatter_shell",
    name: "碎霜外壳",
    rarity: "rare",
    trigger: "onShieldBreak",
    description: "护盾破裂时释放冰霜冲击，造成冰伤并减速。",
    effect: { createAreaDamage: { type: "ice", scaleFromMagicPower: 0.55, radius: 90, applySlow: 0.25 } },
  },
  {
    id: "blood_price_contract",
    name: "血价契约",
    rarity: "epic",
    trigger: "onHealthBelow:35",
    description: "生命低于 35% 时提高攻击力和暴击伤害。",
    effect: { temporaryStats: { attack: 24, critDamage: 0.35, duration: 6 } },
  },
  {
    id: "arcane_echo",
    name: "奥术回声",
    rarity: "rare",
    trigger: "onDamageType:arcane",
    description: "奥术伤害有概率重复触发一次低额奥术伤害。",
    effect: { repeatDamage: { type: "arcane", chance: 0.22, ratio: 0.35 } },
  },
  {
    id: "holy_afterglow",
    name: "圣辉余烬",
    rarity: "rare",
    trigger: "onHit:holy",
    description: "造成神圣伤害后，为最低生命友方回复少量生命。",
    effect: { healAlly: { target: "lowestHpPercent", scaleFromMagicPower: 0.28 } },
  },
  {
    id: "shadow_leech",
    name: "影噬石",
    rarity: "uncommon",
    trigger: "onDamageType:shadow",
    description: "暗影伤害的一部分转化为治疗。",
    effect: { lifeSteal: { damageType: "shadow", ratio: 0.18 } },
  },
  {
    id: "glass_blade",
    name: "玻璃刃",
    rarity: "rare",
    trigger: "passive",
    description: "攻击力和暴击率提高，但最大生命降低。",
    effect: { stats: { attack: 30, critChance: 0.08, hp: -80 } },
  },
  {
    id: "stone_heart",
    name: "石心",
    rarity: "uncommon",
    trigger: "passive",
    description: "防御和魔抗提高，移动速度降低。",
    effect: { stats: { defense: 18, magicResist: 18, moveSpeed: -8 } },
  },
  {
    id: "chain_spark",
    name: "连锁火花",
    rarity: "epic",
    trigger: "onDamageType:lightning",
    description: "闪电伤害有概率跳到额外目标。",
    effect: { chainDamage: { type: "lightning", chance: 0.28, jumps: 2, falloff: 0.65 } },
  },
  {
    id: "oil_soaked_bandage",
    name: "浸油绷带",
    rarity: "rare",
    trigger: "onDamageType:fire",
    description: "火焰伤害命中时提高目标后续受到的火焰伤害。",
    effect: { applyDebuff: { stat: "fireDamageTakenAmp", value: 0.08, duration: 4, maxStacks: 5 } },
  },
  {
    id: "toxic_hourglass",
    name: "毒砂漏",
    rarity: "epic",
    trigger: "onApplyDot:poison",
    description: "剧毒持续时间越久，最后一跳伤害越高。",
    effect: { modifyDotFinalTick: { type: "poison", extraRatioPerSecond: 0.08 } },
  },
  {
    id: "duelist_mark",
    name: "决斗印记",
    rarity: "uncommon",
    trigger: "onBattleStart",
    description: "锁定最近敌人，对其单体伤害提高。",
    effect: { markNearestEnemy: { stat: "singleTargetDamageAmp", value: 0.16 } },
  },
  {
    id: "wildfire_map",
    name: "野火地图",
    rarity: "rare",
    trigger: "onKill:fire",
    description: "火焰击杀时在目标脚下留下燃烧区域。",
    effect: { createGroundDot: { type: "fire", duration: 4, radius: 85, scaleFromMagicPower: 0.18 } },
  },
  {
    id: "ice_lens",
    name: "冰透镜",
    rarity: "rare",
    trigger: "onDamageType:ice",
    description: "冰霜伤害命中已减速目标时，提高暴击率。",
    effect: { conditionalStats: { condition: "targetSlowed", critChance: 0.12 } },
  },
  {
    id: "magebone_dice",
    name: "法骨骰",
    rarity: "epic",
    trigger: "onAttackStart",
    description: "每次攻击随机提高一种元素伤害。",
    effect: { randomElementAmp: { value: 0.14, duration: 3 } },
  },
  {
    id: "war_banner_shard",
    name: "战旗碎片",
    rarity: "rare",
    trigger: "onEverySeconds:5",
    description: "每 5 秒为附近友军提供攻击力。",
    effect: { auraPulse: { stat: "attack", value: 10, duration: 4, radius: 120 } },
  },
];

module.exports = { MAX_RELICS_PER_UNIT, RELICS };

