const RARITIES = [
  { id: "common", name: "普通", multiplier: 1.0, color: "#c8c2b2" },
  { id: "rare", name: "稀有", multiplier: 1.25, color: "#66b8e8" },
  { id: "epic", name: "史诗", multiplier: 1.6, color: "#a783ee" },
  { id: "legendary", name: "传说", multiplier: 2.1, color: "#e7b84f" },
  { id: "mythic", name: "神话", multiplier: 2.75, color: "#ef6f6c" },
  { id: "wonder", name: "惊奇", multiplier: 3.45, color: "#6ce0c5" },
  { id: "phantom", name: "幻影", multiplier: 4.35, color: "#d68cff" },
];

const WORLD_ZONES = [
  {
    id: "grass_camp",
    name: "荒草营地",
    recommendedLevel: 1,
    recommendedPower: 120,
    enemyLevel: [1, 2],
    expReward: [28, 42],
    equipmentTiers: [1, 2],
    rarityTable: { common: 0.58, rare: 0.28, epic: 0.1, legendary: 0.035, mythic: 0.005 },
    enemies: ["草地盗匪", "木盾兵", "野火学徒"],
    map: { x: 12, y: 68, theme: "grass" },
  },
  {
    id: "old_road",
    name: "旧路哨站",
    recommendedLevel: 3,
    recommendedPower: 260,
    enemyLevel: [3, 4],
    expReward: [48, 70],
    equipmentTiers: [2, 3],
    rarityTable: { rare: 0.48, epic: 0.28, legendary: 0.16, mythic: 0.07, wonder: 0.01 },
    enemies: ["铁盔巡卒", "弩手", "灰袍医师"],
    map: { x: 27, y: 55, theme: "road" },
  },
  {
    id: "black_pine",
    name: "黑松林",
    recommendedLevel: 5,
    recommendedPower: 480,
    enemyLevel: [5, 7],
    expReward: [76, 112],
    equipmentTiers: [3, 4, 5],
    rarityTable: { epic: 0.45, legendary: 0.3, mythic: 0.18, wonder: 0.06, phantom: 0.01 },
    enemies: ["林地刺客", "黑松狼", "腐藤术士"],
    map: { x: 42, y: 38, theme: "forest" },
  },
  {
    id: "stone_mine",
    name: "碎石矿坑",
    recommendedLevel: 8,
    recommendedPower: 760,
    enemyLevel: [8, 10],
    expReward: [112, 165],
    equipmentTiers: [5, 6, 7],
    rarityTable: { legendary: 0.42, mythic: 0.32, wonder: 0.18, phantom: 0.08 },
    enemies: ["矿坑傀儡", "爆药工", "碎晶虫"],
    map: { x: 58, y: 62, theme: "mine" },
  },
  {
    id: "mist_marsh",
    name: "雾沼边境",
    recommendedLevel: 10,
    recommendedPower: 1120,
    enemyLevel: [10, 13],
    expReward: [155, 230],
    equipmentTiers: [6, 7, 8],
    rarityTable: { mythic: 0.5, wonder: 0.33, phantom: 0.17 },
    enemies: ["沼泽毒师", "泥甲守卫", "雾中猎手"],
    map: { x: 72, y: 45, theme: "marsh" },
  },
  {
    id: "thunder_highland",
    name: "雷鸣高地",
    recommendedLevel: 15,
    recommendedPower: 1780,
    enemyLevel: [15, 18],
    expReward: [230, 340],
    equipmentTiers: [7, 8, 9],
    rarityTable: { mythic: 0.28, wonder: 0.46, phantom: 0.26 },
    enemies: ["雷斧蛮兵", "风暴祭司", "山脊巨兽"],
    map: { x: 83, y: 24, theme: "thunder" },
  },
  {
    id: "dragon_bone",
    name: "龙骨废墟",
    recommendedLevel: 20,
    recommendedPower: 2600,
    enemyLevel: [20, 24],
    expReward: [330, 520],
    equipmentTiers: [9, 10],
    rarityTable: { wonder: 0.55, phantom: 0.45 },
    enemies: ["龙骨骑士", "星界残魂", "废墟守望者"],
    map: { x: 91, y: 72, theme: "ruin" },
  },
];

module.exports = { RARITIES, WORLD_ZONES };

